### ISSUE TITLE
Présentation générale du lundi et cours du vendredi sur la modélisation des écosystèmes.

### ISSUE THREAD

**Issue by SakinaAyata** [jiho/ML4Oceans#1]
[Ayata_marine_ecosystem_modelling_ML4Oceans_2022.pdf](https://github.com/jiho/ML4Oceans/files/9596948/Ayata_marine_ecosystem_modelling_ML4Oceans_2022.pdf)
[Introduction_ML4Oceans_summer_School_2022.pdf](https://github.com/jiho/ML4Oceans/files/9596950/Introduction_ML4Oceans_summer_School_2022.pdf)

**Comment by jiho** [comment]
Added
